name: Build project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Code Style"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup deps
        uses: ./.github/actions/install-deps

      - name: Build
        run: pnpm build
