name: Test

on:
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup deps
        uses: ./.github/actions/install-deps

      - name: Run unit Tests
        run: pnpm vitest --silent --coverage

      - name: 'Report Coverage'
        uses: davelosert/vitest-coverage-report-action@v2

      - name: 'Upload Coverage'
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
